### ISSUE TITLE
Discussion on Project Topic Selection

### ISSUE THREAD

**Issue by duongllhtuet** [duongllhtuet/ECommerceShop#1]
Hello everyone!

We are currently at a crucial stage in our project - choosing the project topic. This decision is significant as it will impact the direction and ultimate outcome of our project. Please use this thread to discuss, propose ideas, and provide suggestions on the topic we should focus on.

**Comment by UncPham** [comment]
game Heroes 3 :))

**Comment by duongllhtuet** [comment]
Mô tả tổng quan: Dự án của tôi là một ứng dụng web giúp người dùng nâng cao kiến thức và kỹ năng học tập thông qua việc sử dụng flashcards (thẻ học). Ứng dụng này cung cấp một loạt các tính năng học tập, dựa trên cơ sở của ứng dụng nổi tiếng Quizlet, tuy nhiên, với mức độ đơn giản hơn và tập trung vào cung cấp môi trường học tập hiệu quả. Dưới đây là mô tả chi tiết về các tính năng chính của dự án:

Các tính năng cần có:
1. Tạo bộ flashcards cá nhân: Người dùng cũng có khả năng tạo các bộ flashcards của riêng họ. Họ có thể tạo, chỉnh sửa và quản lý các tập học tập cá nhân theo nhu cầu riêng.
2. FlashCard Presentation: Tính năng này cho phép người dùng tạo và trình chiếu danh sách flashcards như một bài giảng học tập. Điều này giúp họ tập trung vào việc học thuộc lòng thông tin quan trọng trên các thẻ học.
3. Learn: Tính năng học cho phép người dùng tiếp cận từng flashcard một. Nội dung trên mỗi thẻ được hiển thị, giúp họ kiểm tra kiến thức và thuộc lòng các chi tiết quan trọng.
4. Test: Tính năng kiểm tra giúp người dùng kiểm tra kiến thức của họ bằng cách hiển thị flashcards và yêu cầu họ trả lời các câu hỏi liên quan.
5. Matching: Tính năng "Matching" cho phép người dùng thực hiện các bài tập tương tự như trò chơi "Matching" trên Quizlet. Họ phải nối các cặp flashcards tương đương để kiểm tra kiến thức.
6. Search: Tính năng tìm kiếm cho phép người dùng tìm kiếm và truy cập các flashcards dựa trên từ khoá hoặc chủ đề cụ thể.
7. Spaced Repititions: Tính năng nhắc nhở người dùng ôn tập để tăng ghi nhớ sau một thời gian nhất định.

Công nghệ và ngôn ngữ sử dụng:
Phía Client:
Sử dụng React và các thư viện liên quan để xây dựng giao diện người dùng.
Sử dụng Axios để giao tiếp với máy chủ.
Sử dụng Redux Toolkit để quản lý trạng thái ứng dụng.
Sử dụng các thư viện như Emotion, Font Awesome và Material-UI để tạo giao diện người dùng thân thiện và hiện đại.
Phía Server:
Sử dụng Node.js để xây dựng máy chủ.
Sử dụng Express.js làm framework web.
Sử dụng Sequelize và MySQL2 để quản lý cơ sở dữ liệu.
Sử dụng JWT (JSON Web Tokens) để xác thực và đảm bảo tính bảo mật cho người dùng.

**Comment by tronganh0104** [comment]
Về phần mềm tôi muốn đề xuất là phần mềm học tiếng Anh. Giúp người dùng cải thiện kĩ năng nghe, nói, đọc, viết
Các tính năng: 
- Đăng nhập và đăng ký
- Tự tạo một bộ từ vựng của bản thân bằng cách tra từ
- Đăng tải bộ từ vựng lên cộng đồng
- Học bộ từ vựng bằng cách trả lời các đáp án trắc nghiệm, gõ văn bản hoặc nói
- Có các nhiệm vụ hằng ngày cho người dùng
- Tìm kiếm các bộ từ vựng mong muốn
Những công cụ sử dụng:
- Ngôn ngữ lập trình: Python
- API: Google Cloud Speech-to-Text API và Google Translate API
- Cơ sở dữ liệu MongoDB

**Comment by UncPham** [comment]
Phần mềm mình muốn đề xuất là Heroes of Might and Magic III: The Shadow of Death

- Mô tả: Heroes of Might and Magic III: The Shadow of Death là trò chơi chiến lược theo lượt được phát triển bởi Jon Van Caneghem tại hãng New World Computing và công ty The 3DO Company
- Các tính năng:
    - Cách chơi game giống như bản gốc
    - Chơi với nhiều người chơi bằng LAN
    - Tạo map ngẫu nhiên
- Công cụ và ngôn ngữ sử dụng
    - Công cụ Godot và ngôn ngữ C#
